### ISSUE TITLE
Implement Github signin

### ISSUE THREAD

**Issue by toystars** [mentorpaired/frontend#40]
Acceptance Criteria:

Users should be able to authenticate with Github.

NB: Redirects to Dashboard after authentication

**Comment by devraulu** [comment]
I'll do my best to have it done by the end of the week (Sunday)

**Comment by devraulu** [comment]
I spent most of the time setting up the core of the project, therefore I'm going to need extra time to get this done, hopefully, this week by Thursday.

**Comment by devraulu** [comment]
Still dealing with some errors with the core, I'm going to set a deadline when the errors are fixed.
