### ISSUE TITLE
Implement Dashboard page blueprint

### ISSUE THREAD

**Issue by toystars** [mentorpaired/frontend#42]
Acceptance Criteria:

After signin, users should see the dashboard with two sections:

- Navigation tabs section (Including call to action button)
- Content section

Navigation tabs section design should also be implemented.

See design below:

<img width="1045" alt="Screenshot 2020-11-15 at 9 03 39 PM" src="https://user-images.githubusercontent.com/16062709/99195918-1a4a1e80-2789-11eb-8f5d-2c28c79bdd32.png">

**Comment by ArinzeJeffrey-droid** [comment]
I'll have this done by Sunday.
